# Generated by Django 3.1.7 on 2021-04-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_auto_20210331_1902'),
        ('employer', '0003_auto_20210401_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFavoriteVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('employer', models.ManyToManyField(related_name='employers', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='AddFavoriteCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('cvs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='employee.cv')),
                ('employee', models.ManyToManyField(related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
