# Generated by Django 3.1.7 on 2021-03-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.ImageField(default='img/user-placeholder.png', upload_to='users/%Y/%m/%d/', verbose_name='Фото')),
                ('position_seek', models.CharField(max_length=250, verbose_name='желаемая должность')),
                ('compensation_seek', models.PositiveIntegerField(verbose_name='желаемая зарплата')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='отчество')),
                ('family_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, verbose_name='пол')),
                ('birthday', models.DateField(verbose_name='день рождения')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('profession', models.CharField(max_length=150, verbose_name='профессия')),
                ('skills', models.CharField(max_length=150, verbose_name='навыки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('is_checked', models.BooleanField(default=True, verbose_name='проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at', 'family_name'],
            },
        ),
        migrations.CreateModel(
            name='JobExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150, verbose_name='работодатель')),
                ('employer_link', models.URLField(blank=True, max_length=150, verbose_name='ссылка')),
                ('position', models.CharField(max_length=150, verbose_name='должность')),
                ('start_at', models.DateField(verbose_name='начало работы')),
                ('finish_at', models.DateField(verbose_name='дата увольнения')),
                ('duties', models.TextField(verbose_name='обязанности')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employee.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150, verbose_name='название учебного заведения')),
                ('specialization', models.CharField(max_length=150, verbose_name='специальность')),
                ('grade', models.CharField(choices=[('БАКАЛАВР', 'Бакалавр'), ('МАГИСТР', 'Магистр'), ('ДОКТОР', 'Доктор'), ('СПЕЦИАЛИСТ', 'Специалист')], max_length=150, verbose_name='степень')),
                ('graduated_at', models.DateField(verbose_name='окончание учебы')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee.cv')),
            ],
        ),
    ]
