# Generated by Django 3.1.7 on 2021-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college_name',
            field=models.CharField(max_length=150, verbose_name='Учебное заведение'),
        ),
    ]
