# Generated by Django 3.1.7 on 2021-03-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_jobexp_employer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobexp',
            name='duties',
        ),
        migrations.AlterField(
            model_name='cv',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
