# Generated by Django 3.1.7 on 2021-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210325_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='user',
            new_name='created_by',
        ),
    ]
