# Generated by Django 3.1.7 on 2021-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210326_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexp',
            options={'ordering': ['-finish_at'], 'verbose_name': 'Опыт работы'},
        ),
    ]
