# Generated by Django 3.1.7 on 2021-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojobuser',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='infojobuser',
            name='password',
            field=models.CharField(max_length=250, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='infojobuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='пользователь'),
        ),
    ]
