# Generated by Django 3.1.7 on 2021-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210313_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojobuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='infojobuser',
            name='email',
            field=models.EmailField(blank=True, max_length=150, unique=True),
        ),
    ]
