# Generated by Django 3.1.7 on 2021-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210331_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojobuser',
            name='password',
            field=models.CharField(max_length=50, verbose_name='пароль'),
        ),
    ]
