# Generated by Django 3.1.7 on 2021-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210331_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojobuser',
            name='user_role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('EMPLOYER', 'Employer')], max_length=25, verbose_name='роль'),
        ),
    ]
