# Generated by Django 3.1.7 on 2021-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210331_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojobuser',
            name='password',
            field=models.CharField(max_length=250, verbose_name='пароль'),
        ),
    ]
