# Generated by Django 3.1.7 on 2021-03-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('industry_name', models.CharField(max_length=150, verbose_name='индустрия')),
                ('logo_pic', models.ImageField(default='companies/logo-placeholder.png', upload_to='companies/%Y/%m/%d/', verbose_name='Логотип')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('site_link', models.URLField(blank=True, max_length=150, verbose_name='ссылка на сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_checked', models.BooleanField(default=True, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, verbose_name='должность')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('duties', models.TextField(verbose_name='обязанности')),
                ('compensation', models.PositiveIntegerField(verbose_name='зарплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('is_checked', models.BooleanField(default=True, verbose_name='проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.company')),
            ],
        ),
    ]
