# Generated by Django 3.1.7 on 2021-03-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(upload_to='companies/%Y/%m/%d/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_invitation', to='employer.company'),
        ),
    ]
